### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by somedevreally** [Xtrendence/Cryptofolio#11]
when i do docker pull xtrendence/cryptofolio
i get this error
```
Using default tag: latest
Error response from daemon: manifest for xtrendence/cryptofolio:latest not found: manifest unknown: manifest unknown
```

**Comment by Xtrendence** [comment]
Try doing "docker pull xtrendence/cryptofolio:v.1.0" maybe. It's my first time using Docker, so I apologize if I don't know too much about it, but in this case I think it's because the image on Docker has the tag v.1.0 whereas just doing "docker pull" would use the tag "latest" which doesn't exist. On Mar 30, 2021 7:33 PM, somedevreally ***@***.***> wrote:
when i do docker pull xtrendence/cryptofolio
i get this error
Using default tag: latest
Error response from daemon: manifest for xtrendence/cryptofolio:latest not found: manifest unknown: manifest unknown

**Comment by somedevreally** [comment]
thanks, got it. after adding v.1.0.
i think there is no :latest tag for dockerhub image

also i was able to create docker-compose, it works.
```
version: '3'
services:
  cryptofolio:
    image: xtrendence/cryptofolio:v.1.0
    ports:
      - 8080:80
    container_name: cryptofolio
    restart: always
```

is there a way to add volume? so dont have to do `chown -R www-data:www-data /var/www/html/` for each container up
