### ISSUE TITLE
Invalid JSON on login

### ISSUE THREAD

**Issue by Xyrodileas** [Xtrendence/Cryptofolio#15]
Hello,

I tried to start the docker image with the tag v.1.0 and got the following error : 
![image](https://user-images.githubusercontent.com/2392017/113898640-0cc61d00-979a-11eb-85b3-5f6b07581d9d.png)

docker-compose used :
```
version: "3"
services:

  cryptoportfolio:
    image: xtrendence/cryptofolio:v.1.0
    # ports:
    #   - "2222:2222"   # scryptofolio
    #   - "80:8080" # http backup port
    environment:
      ServerName: crypto.${HOMELAB_DOMAIN}
    labels:
      - traefik.enable=true
      - "traefik.http.routers.cryptofolio-secure.entrypoints=websecure"
      - "traefik.http.routers.cryptofolio-secure.rule=Host(`crypto.${HOMELAB_DOMAIN}`)"
      - "traefik.http.routers.cryptofolio-secure.tls=true"
      - "traefik.http.routers.cryptofolio-secure.service=cryptofolio"
      - "traefik.http.routers.cryptofolio-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.cryptofolio.loadbalancer.server.port=80"
      - "traefik.docker.network=transit"
    #  - "traefik.http.routers.cryptofolio-secure.middlewares=openid-traefik"
    restart: unless-stopped
    networks:
      - transit

networks:
  transit:
     external: true
```
